runtime = { FetchVersion = "0.4.0-1cbc110" }
runtime_build_verbose = false


[[tests]]

setup_package_paths = ["chat"]
test_package_paths = ["sqlite_test", "key_value_test", "chat_test"]
package_build_verbose = false

[tests.network_router]

port = 9001
defects = "None"  # Plan to include Latency, Dropping, ..., All

[[tests.nodes]]

port = 8080
home = "home/first"
fake_node_name = "first.uq"
runtime_verbose = false

[[tests.nodes]]

port = 8081
home = "home/second"
fake_node_name = "second.uq"
runtime_verbose = false


[[tests]]

setup_package_paths = []
test_package_paths = ["key_value_test"]
package_build_verbose = false

[tests.network_router]

port = 9001
defects = "None"  # Plan to include Latency, Dropping, ..., All

[[tests.nodes]]

port = 8080
home = "home/first"
fake_node_name = "first.uq"
runtime_verbose = false
