runtime = { FetchVersion = "latest" }
# runtime = { RepoPath = "~/git/kinode" }
runtime_build_release = false


[[tests]]
setup_package_paths = []
test_packages = [
    { path = "key_value_test", grant_capabilities = ["kv:distro:sys"] },
    { path = "sqlite_test", grant_capabilities = ["sqlite:distro:sys"] },
]
setup_scripts = []
test_scripts = []
timeout_secs = 5
fakechain_router = 8545

[[tests.nodes]]
port = 8080
home = "home/first"
fake_node_name = "first.dev"
runtime_verbosity = 0

[[tests.nodes]]
port = 8081
home = "home/second"
fake_node_name = "second.dev"
runtime_verbosity = 0


[[tests]]
setup_package_paths = []
test_packages = [
    { path = "key_value_test", grant_capabilities = ["kv:distro:sys"] }
]
setup_scripts = []
test_scripts = []
timeout_secs = 5
fakechain_router = 8545

[[tests.nodes]]
port = 8080
home = "home/first"
fake_node_name = "first.dev"
runtime_verbosity = 0
