# runtime = { FetchVersion = "0.4.0-5903a5a" }
runtime = { RepoPath = "~/path/to/repo/nectar" }
runtime_build_verbose = false


[[tests]]

setup_package_paths = ["chat"]
test_packages = [{ path = "chat_test", grant_capabilities = ["chat:chat:nectar"] }]
# test_package_paths = [{ path = "sqlite_test", grant_capabilities = [] }, { path = "key_value_test", grant_capabilities = [] }, { path = "chat_test", "grant_capabilities" = ["chat:chat:nectar"] }]  # TODO: reenable
package_build_verbose = false
timeout_secs = 5

[tests.network_router]

port = 9001
defects = "None"  # Plan to include Latency, Dropping, ..., All

[[tests.nodes]]

port = 8080
home = "home/first"
fake_node_name = "first.nec"
runtime_verbose = false

[[tests.nodes]]

port = 8081
home = "home/second"
fake_node_name = "second.nec"
runtime_verbose = false


# # TODO: reenable
# [[tests]]
#
# setup_package_paths = []
# test_package_paths = [{ path = "key_value_test", grant_capabilities = [] }]
# package_build_verbose = false
# timeout_secs = 5
#
# [tests.network_router]
#
# port = 9001
# defects = "None"  # Plan to include Latency, Dropping, ..., All
#
# [[tests.nodes]]
#
# port = 8080
# home = "home/first"
# fake_node_name = "first.nec"
# runtime_verbose = false
