# Set to appropriate directories for your system

runtime_path = "~/git/uqbar"


[[tests]]

test_process_paths = ["sqlite_test", "key_value_test"]

[[tests.nodes]]

port = 8080
home = "~/uqbar-home"
password = "secret"
rpc = "wss://eth-sepolia.g.alchemy.com/v2/<your-api-key>"
is_runtime_print = true


[[tests]]

test_process_paths = ["key_value_test"]

[[tests.nodes]]

port = 8080
home = "~/uqbar-home"
password = "secret"
rpc = "wss://eth-sepolia.g.alchemy.com/v2/<your-api-key>"
is_runtime_print = true
